name: 💪 100% test 
on: [push, workflow_dispatch]
jobs:
  coverage:
    runs-on: macos-latest-xlarge # ubuntu-latest causes more than a 1% diff in goldens
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
    - uses: hrishikesh-kadam/setup-lcov@v1

    - run: sh coverage.sh
    